// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SociFilarmonicaDesktop.Data;

namespace SociFilarmonicaDesktop.Migrations
{
    [DbContext(typeof(FilarmonicaContext))]
    [Migration("20191214152636_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("SociFilarmonicaDesktop.Models.Socio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipologiaSocioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("TipologiaSocioID");

                    b.ToTable("Socio");
                });

            modelBuilder.Entity("SociFilarmonicaDesktop.Models.TipologiaSocio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TipologiaSocio");
                });

            modelBuilder.Entity("SociFilarmonicaDesktop.Models.Socio", b =>
                {
                    b.HasOne("SociFilarmonicaDesktop.Models.TipologiaSocio", "Tipologia")
                        .WithMany("SociDiCategoria")
                        .HasForeignKey("TipologiaSocioID");
                });
#pragma warning restore 612, 618
        }
    }
}
